language: node_js
node_js: node
services:
- mongodb
deploy: 
  provider: heroku
  api_key: 
    secure: 180fbe96-837a-4b42-b7cd-83983511db9d
  app: infinite-sierra-98210
  on:
    repo: avanichyanukroh/circle.it
