language: node_js
node_js: node
services:
- mongodb
deploy: 
  provider: heroku
    secure: ojUQEfoR5edA3bCCfZOpryMoJ4cIsXtu7KqO9mrQjPDffnOcDHviwleIMyJWmX2w2Fw0NPj3ytjCji1HYLRX8fHpRUgtqWaMwbJiVbVvDYF/P+BaXd4q0RLBu9UUjQoS0dYn6lSKE1AmqQv2tRpttnW8t+dF+tAuFdbNOua+kvyJOewReg6VA5ZKGpb19QeL6LgNRAAnRi2L+om2/wO1HLpgyCcGuytpSfQSLlLOLKvcgum2zhLGFiK6Z5KINQOijvYBEV03zVtT6ImaEBDNx0WeWkYs0Pa8jimuNjvN2xoGDlgctvxm95lckpZN5EAKUsPkPwL4nedtFQFeX1NbJB8eHxYg0dttpNBJB6SgOP/3O4ZlY1lMtHNPwQpUxegulMqMrnV6P2Ol43Rdbiy39Bf7+IhzB9GVBWOzCPKU+X6+PDaEzCnY6tJKrjJJjvTFnqQoWXCtAKBiLOt5E2zVgLGWGtwYmpKzMdExjGKOZgHYHCsMaAB5AmlxNgzJNw8Ay/a2YKcqE/bSSUHWVAwkFxAFgNJ4tEXVJ+Dani6z/NNDIljiVAB13agMNHUkBMrsgn9yBTA4DW6ZYOrLe+k/7vUOWoFr68ENOFhfkkeGW3qqIP/5t3ezT6KRJ03GlBmSkuS+gcgOpesY2AmUzqNhgdFx8mHu/bAnAn4p9Uo7dXE=
  app: infinite-sierra-98210
  on:
    repo: avanichyanukroh/circle.it
