language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: X6XIzYgSXVWLaSPYHiWD41N1nRGkR9KjZ36v1Zouu51rErMVmbFYNZBVfNpD+w6DjMzNzHhtzm4p9iO8AolChTXRlCM6oT0b1KNjq/f/HdFt1jKCMwdKa1ABxGC2lAQLFcZR77wtSs9kUrqqf9QziGLg8N+Fqz5pdv4OAIOsu1p9RpVv9bUATqhYbN6veenYWNnX4SjL0LPCLRwsyK85z3GlqmgYWJLYKCPUq20h9HhhI6FZhO3D6nZeN5ST86t9TzDKAXDuFOT66PKsVaqr7RSl8X/iKQZ6Q4seOidagsZ6XCzcYXFXsZkKqz1RYtLbUACxMzgg8+cRZCm7s0J2w91d0/SvmS6JWPt7DSoRLHnXnkzCIgM19S34d1FfQhyd8UCAwLB8QtW792X4qI3UNCYFyAFxoPeBAIsMBHyk5UCv8qUubraNb5n/0j8z4NWrg5aolqypvk4L0WDcieGewsySQFSvSoQM9dgwO8Nol8uawiO3i5XttfSswusAbDtxUczN6A6MXZY9/JSsxh8Dq5EhIQK6Livvd9CF/3j0FWlh21VhupP2qCUrawcUBCXqCKYpI6ey+9dbDRg3g9qbAOY2R0saQ3zapVrSbhBEmUcMIkfotxAGSk8Lipr3uIFoUj2ej9IIMtaSWsZNUaGVN9j927a3vJeTmLDgbolUW/0=
  app: infinite-sierra-98210
  on:
    repo: avanichyanukroh/circle.it
